"""Update transaction_list to MutableList

Revision ID: 2cb3dc241c32
Revises: c602c4bd198e
Create Date: 2024-07-13 21:45:21.436640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb3dc241c32'
down_revision: Union[str, None] = 'c602c4bd198e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
