"""Update transaction_list to MutableList

Revision ID: 406582bf66a4
Revises: 9d97316b2b99
Create Date: 2024-07-13 23:13:42.450680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406582bf66a4'
down_revision: Union[str, None] = '9d97316b2b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
