"""Update transaction_list to MutableList

Revision ID: 8f77c94e67c4
Revises: 2cb3dc241c32
Create Date: 2024-07-13 21:49:54.762372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f77c94e67c4'
down_revision: Union[str, None] = '2cb3dc241c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
