"""Add user, balance, request tables

Revision ID: af5f56c0c3d7
Revises: daaa122a5d8b
Create Date: 2024-07-23 06:52:42.922492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5f56c0c3d7'
down_revision: Union[str, None] = 'daaa122a5d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
